# # Generated by Django 4.2 on 2023-04-05 10:41
from django.db import migrations, models


def set_separated_employees_full_name(apps, schema_editor):
    Employee = apps.get_model('company_api', 'Employee')
    employees_queryset = Employee.objects.all()

    for employee in employees_queryset:
        name_parts = employee.full_name.split()

        employee.name = name_parts[0]
        employee.surname = name_parts[1]
        employee.middle_name = name_parts[2]
        employee.save()


def reverse_set_separated_employees_full_name(apps, schema_editor):
    Employee = apps.get_model('company_api', 'Employee')
    employees_queryset = Employee.objects.all()

    for employee in employees_queryset:
        full_name = ' '.join([
            employee.name,
            employee.surname,
            employee.middle_name
        ])
        employee.full_name = full_name.strip()
        employee.save()


class Migration(migrations.Migration):

    dependencies = [
        ('company_api', '0002_alter_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='surname',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.RunPython(
            set_separated_employees_full_name,
            reverse_set_separated_employees_full_name,
            atomic=False,
        ),
        migrations.RemoveField(
            model_name='employee',
            name='full_name',
        ),
    ]
