# # Generated by Django 4.2 on 2023-04-05 10:41
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_api', '0002_alter_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='surname',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
