# Generated by Django 4.2 on 2023-04-07 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_api', '0004_separate_full_name_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='full_name',
        ),
]


